### ISSUE TITLE
Add additional tools to workflow

### ISSUE THREAD

**Issue by leeprichman** [immune-health/antigen.garnish#101]
- [ ] [DeepMHC](https://www.biorxiv.org/content/early/2017/12/24/239236)
- [ ] [DIAMOND](https://www.ncbi.nlm.nih.gov/pubmed/29771282?dopt=Abstract)
+ implement
+ benchmark iedb_score against BLAST

**Comment by andrewrech** [comment]
Done in forthcoming publication
