### ISSUE TITLE
mkdir: cannot create directory ‘/scratch’: Permission denied

### ISSUE THREAD

**Issue by itamuria** [immune-health/antigen.garnish#120]
Dear developer, 

I am trying to run the first example of the website:

`
library(magrittr)
library(data.table)
library(antigen.garnish)`
	`dir <- system.file(package = "antigen.garnish") %>% file.path(., "extdata/testdata")
	dt0 <- "antigen.garnish_example.vcf" %>% file.path(dir, .) %>% garnish_variants %>% .[, MHC := c("HLA-A*01:47 HLA-A*02:01 HLA-DRB1*14:67")] %>% garnish_affinity2`

and I am obtaining the next error:
`Running netMHC in parallel mkdir: cannot create directory ‘/scratch’: Permission denied`

How could I give writing permission to netMHC?
Thanks, 
All the best, 
Ibon

**Comment by leeprichman** [comment]
Hi Ibon,

This appears to be netMHC trying to create temporary folders for itself, not any of our code being executed. As indicated in the README, `antigen.garnish` requires `sudo` permissions to install and execute. Ideally you will need to get administrator privileges or be the root user on your system. You should also make sure the home directory is set to one that you have full permissions for.

If you need an alternative solution, you can visit the [wiki](https://github.com/immune-health/antigen.garnish/wiki) for instructions on how to use `antigen.garnish` with Docker and Amazon Web Services.

**Comment by leeprichman** [comment]
Hi Ibon,

I hope you were able to resolve this issue! I'm going to close this soon if you don't have any further questions.
