### ISSUE TITLE
netMHC data lose ?

### ISSUE THREAD

**Issue by xf78** [immune-health/antigen.garnish#121]
Hi,dear team,
i have installed antigen.garnish an it's dependentce files,
i make a test and have made a mistake,my code as blew:

> v <- c("SIINFEKL", "ILAKFLHWL", "GILGFVFTL")
> 
> # calculate IEDB score
> v %>% iedb_score(db = "human") %>% print
Checking netMHC scripts in antigen.garnish data directory.

and the terminal is hang on,netMHC data lose?

**Comment by leeprichman** [comment]
It's hard for me to understand the issue without more information. This appears to be during the attempted configuration of the netMHC scripts. Were you able to download all four netMHC programs from DTU after agreeing to their license and execute the code in the README to move the appropriate files into the antigen.garnish data directory?

**Comment by leeprichman** [comment]
Hi xf78,

I'm going to close out this issue in a day or two if you don't have any updates. Please reopen it if there is anything further.
