### ISSUE TITLE
Why is it downloading each time?

### ISSUE THREAD

**Issue by itamuria** [immune-health/antigen.garnish#122]
Hello, 

I am testing the software and each time I run it, it looks that it is downloading data. And it takes long time. Is there any option to don't download each time? 

```
Done loading variants.
Reading local transcript metadata.
Checking netMHC scripts in antigen.garnish data directory.
Downloading data for netMHCII-2.3 on Linux
```

I have seen that there is something strange in the function called **configure_netMHC_tools** where the function searches binaries in mhc folder. 

"netMHC-4.0/netMHC"           
"netMHCII-2.3/netMHCII"      
"netMHCII-2.3/netMHCII-2.3"   
"netMHCIIpan-3.2/netMHCIIpan" 
"netMHCpan-4.0/netMHCpan"    

In the case of netMHCII there are two possible netMHC and it could become a problem. 

Thanks, 
Ibon

**Comment by leeprichman** [comment]
Hi Ibon,
The intended function is for the supplemental data to be downloaded from DTU only once. A check is run to ensure that the netMHC scripts have been reconfigured and supplemental data is downloaded. I would delete the antigen garnish data directory and reinstall, then make sure you run the script to copy the binaries into the antigen garnish data directory from the README before testing again.  Make sure you are only using a single version of each netMHC algorithm (netMHCI and II, netMHCpan I and II, 4 total). Any more than that could be causing this bug.

**Comment by itamuria** [comment]
Hi Lee, 
I realized that I had some problems with tcsh. After removing and reinstalling every thing is going fine. 
Thanks, 
All the best, 
Ibon
