### ISSUE TITLE
Process Killed

### ISSUE THREAD

**Issue by itamuria** [immune-health/antigen.garnish#135]
Hello, 

I am working with the docker in a MacBook with 16 Gigabytes of RAM. I follow all the instructions and everything looks to working well but after "Predicting affinities" the process is killed and R is crashing. 

Why could it happen?

```
Read 100 items
Running mhcflurry in parallel. 
Input file 1 of 3
Input file 2 of 3
Forcing tensorflow backed
Forcing tensorflow backed
Read input CSV with 270 rows, columns are: allele, pepetide
Read input CSV with 270 rows, columns are: allele, pepetide
Predicting processing
Predicting processing
Predicting affinities
Predicting affinities
Killed 
root@a46c6a45:/#
```

**Comment by leeprichman** [comment]
Docker will set a maximum container memory allotment that may be less than your maximum 16GB. I would first check the settings on the docker desktop app and increase them substantially before trying again. Let me know if that works or not.

**Comment by itamuria** [comment]
It worked! thanks Lee!
