### ISSUE TITLE
Detailed analysis vignette

### ISSUE THREAD

**Issue by leeprichman** [immune-health/antigen.garnish#94]
@davidballi Are you still interested in working on this?  Would be great to have a fresh perspective write this.  I have some svgs that might be useful, the half-baked vignette in andrewrech/antigen.garnish@vignette, and we can use either the example vcfs and tables that we use for testthat, or I have some public data we can host using the same mirror which might be interesting to look at.

Ideally this would cover VCF, fusion, and direct input to the package, and then a quick hit on garnish_summary, garnish_plot, and garnish_targets for the output.  This is no small task and will take some time so let me know how I can help if this is still on your to do list!

**Comment by davidballi** [comment]
Yes I would like to work up a vignette if its cool with you and Andrew.  I'd prefer to use public vcfs where possible to help with end-user reproducibility and real world runtime analysis.  I was thinking some of the vcfs in the van allen dataset?

**Comment by leeprichman** [comment]
Absolutely cool with us.  I was actually thinking that too.  We can host some vcfs on the mirror (I have a version of them already from the Greenbaum et al. supplemental), or are they easily accessible publicly somewhere without some kind of NIH login?

**Comment by andrewrech** [comment]
Done in forthcoming publication
